### ISSUE TITLE
Missing DeleteRowsEvent when resuming

### ISSUE THREAD

**Issue by aichemzee** [noplay/python-mysql-replication#252]
When I resume the logs at position `3468948`
I get the following events with their position: 
`<pymysqlreplication.event.RotateEvent object at 0x112179ef0>
0
<pymysqlreplication.event.QueryEvent object at 0x112179ac8>
3469103
<pymysqlreplication.row_event.DeleteRowsEvent object at 0x1121795c0>
3477394
<pymysqlreplication.row_event.DeleteRowsEvent object at 0x112179630>
3485606
<pymysqlreplication.row_event.DeleteRowsEvent object at 0x112179438>
3486270`

Resuming at `3469103`
gives me:

`<pymysqlreplication.event.RotateEvent object at 0x1123bb518>
0
<pymysqlreplication.row_event.DeleteRowsEvent object at 0x1123bbc18>
3477394
<pymysqlreplication.row_event.DeleteRowsEvent object at 0x1123bbda0>
3485606
<pymysqlreplication.row_event.DeleteRowsEvent object at 0x1123bbe48>
3486270`

But resuming at `3477394` gives me:

`<pymysqlreplication.event.RotateEvent object at 0x1122dc828>
0`

I am only including the following events : [RotateEvent, DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent, QueryEvent]. These delete row events were triggered as a part of a delete query (delete where id < 1000).

My question is that is this expected behavior? Is there a way to resume for each delete row event?

**Comment by kjschiroo** [comment]
We ran into a similar sort of issue. I can't tell you what exactly is going on, but we found a solution in being really selective about where we start and stop streaming. We've found that if you wait for a

```
pymysqlreplication.event.QueryEvent
```

and then only stop and resume on those events you get all of the row events. I would guess that it could work for more than just `QueryEvent`s, but it is the one we've tested.

This does add a little bit of confusion those since it appears these events can appear on a log file boundary and the log file of the stream advances on iteration. This means that you can iterate on the stream, get a record, then check the log file of the stream and have that log file actually be the log file of the next record, not of the record you just got.

**Comment by baloo** [comment]
I would recommend to stop on `XidEvent` (commits) and restarting from there. Our use case uses gtid and we do not rely on binary position, but only on gtid. That works great.

As for the expected behavior, please check with mysql source-code. We do send the position as-this and do not re-encode it. If mysql does not react the way you expect, I would recommend to file a bug against mysql.

**Comment by kjschiroo** [comment]
@baloo Is there a way I resuming a stream on a gtid? I hadn't realized that, I thought filename and binary position was the only option.

Regarding the position, it isn't so much that it is getting munged, it's just that it comes from two different places, at least as I understand it. A record only has it a binary position, and the stream only has the log file. The two need to be used together to get a tuple to resume on, right? If the record comes at the very end of the stream, its binary position might no longer be in reference to the current log file of the stream, but the previous one.

**Comment by baloo** [comment]
When a mysql client starts replication, it gives position and filename to the master for it to open the file it has on disk, skip up to position and stream the content to you from there.
So yeah, you need the tuple.

One thing I find hard personally with filename/position (non-gtid replication) is when you switch master. It is very hard (requires manual inspection of binlog) to convert position read from one master to another.

That's where gtid comes into play. Each transaction on a master/slave topology is given a unique identifier that is shared among all masters in the topology.
https://dev.mysql.com/doc/refman/5.6/en/replication-gtids-concepts.html

I **can't recommend enough** to have a look at gtid. To me it has been a life-changer.
When connecting with gtid replication, the slave would give a master it's current state (gtid set), master would then open sequentially all binlog files it has, read headers of each, determine which file is to be used, then scan the file to find the corresponding gtid, and start streaming data again.

One caveat of this approach is that master has potentially to read a lot of data (multiple GB, depending on your binlog size), to start streaming data to you again.
This may cause latency, one workaround to that, is to increase the number of files and lower the size of 
binlogs (that's what we did).

Our client at $job of python-mysql-replication is relying on gtid extensively. Basically we look for GtidEvent, start buffering data from there, look for XidEvent and replay changes according to our logic.

To be noted: A transaction in mysql binlog, may be started and **canceled** (although this is rare, and almost never occurs). You may want to *not take actions* before XidEvent.
